[project]
name = "jax_pixtral"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.1",
    "huggingface-hub[cli]>=0.34.4",
    "jax[cuda12]>=0.6.2",
    "pillow>=11.2.1",
    "regex>=2025.7.34",
    "safetensors>=0.5.3",
]

